import type { GameState, Personality, Stats } from '../game';
export type StoryEventId='lost_bird'|'moon_flower'|'rival_tracks'|'quiet_rain'|'starlight_market'|'old_shrine'|'firefly_path'|'training_bell'|'winter_letter'|'guardian_dream';
type PersonalityKey=keyof Personality;
export type LegacyStoryState={monthsCompleted?:number;eventHistory?:StoryEventId[];activeEventId?:StoryEventId};
type StoryInput=GameState&LegacyStoryState;
type StoryView=GameState&{monthsCompleted:number;eventHistory:StoryEventId[];activeEventId?:StoryEventId};
export interface StoryEventChoice{id:string;label:string;statDelta?:Partial<Stats>;personalityDelta?:Partial<Personality>;goldDelta?:number}
export interface StoryEventDefinition{id:StoryEventId;title:string;body:string;choices:StoryEventChoice[];eligibility:(state:StoryView)=>boolean}
const legacyMonths=(state:GameState&LegacyStoryState)=>{const value=state.monthsCompleted;return Number.isFinite(value)?Number(value):Math.max(0,(state.year-1)*12+state.month-4)};
const eventHistory=(state:GameState&LegacyStoryState)=>Array.isArray(state.eventHistory)?state.eventHistory:[];
const eventView=(state:GameState&LegacyStoryState):StoryView=>({...state,monthsCompleted:legacyMonths(state),eventHistory:eventHistory(state)} as StoryView);
const clamp=(v:number)=>Math.max(0,Math.min(100,v));
export const STORY_EVENTS:StoryEventDefinition[]=[
{id:'lost_bird',title:'숲속의 작은 손님',body:'길가에서 날개를 다친 작은 새가 루나를 바라보고 있어요.',eligibility:s=>s.personality.kindness>=45,choices:[{id:'help',label:'함께 돌봐준다',statDelta:{affection:3,morality:3},personalityDelta:{kindness:3}},{id:'observe',label:'안전한 곳까지 지켜본다',statDelta:{intelligence:2},personalityDelta:{calmness:2}}]},
{id:'moon_flower',title:'달빛 약초',body:'평소에는 보이지 않던 은빛 약초가 달빛 아래 피어났어요.',eligibility:s=>s.mastery.herb.xp>=1||s.stats.intelligence>=32,choices:[{id:'study',label:'조심스럽게 관찰한다',statDelta:{intelligence:3},personalityDelta:{curiosity:2}},{id:'leave',label:'다음 계절을 위해 남겨둔다',statDelta:{morality:2},personalityDelta:{kindness:2,calmness:1}}]},
{id:'rival_tracks',title:'낯선 발자국',body:'훈련장 근처에서 강한 마력과 함께 낯선 발자국을 발견했어요.',eligibility:s=>s.personality.courage>=52||s.mastery.hunt.xp>=2,choices:[{id:'follow',label:'루나와 흔적을 따라간다',statDelta:{strength:2},personalityDelta:{courage:3}},{id:'prepare',label:'먼저 준비를 단단히 한다',statDelta:{intelligence:2},personalityDelta:{calmness:2}}]},
{id:'quiet_rain',title:'비 오는 오후',body:'창밖에 비가 내려요. 오늘만큼은 천천히 시간을 보내도 좋을 것 같아요.',eligibility:s=>s.stats.fatigue>=25||s.stats.stress>=25,choices:[{id:'rest',label:'따뜻하게 함께 쉰다',statDelta:{fatigue:-10,stress:-8,affection:2},personalityDelta:{calmness:2}},{id:'talk',label:'차를 마시며 이야기를 나눈다',statDelta:{stress:-5,affection:4},personalityDelta:{kindness:2}}]},
{id:'starlight_market',title:'별빛 시장의 밤',body:'여행 상인들이 모인 시장에서 루나가 반짝이는 물건을 발견했어요.',eligibility:s=>s.monthsCompleted>=3,choices:[{id:'explore',label:'루나가 고르게 맡긴다',statDelta:{affection:2},personalityDelta:{curiosity:3}},{id:'save',label:'추억만 담고 돌아온다',goldDelta:120,personalityDelta:{calmness:2}}]},
{id:'old_shrine',title:'오래된 수호 제단',body:'숲 깊은 곳의 작은 제단이 루나의 기척에 은은하게 빛나요.',eligibility:s=>s.monthsCompleted>=6&&s.memories.length>=3,choices:[{id:'promise',label:'앞으로도 함께하겠다고 약속한다',statDelta:{affection:5,morality:2},personalityDelta:{kindness:2}},{id:'listen',label:'조용히 오래된 이야기를 듣는다',statDelta:{magic:3,intelligence:2},personalityDelta:{curiosity:2,calmness:2}}]},
{id:'firefly_path',title:'반딧불이 길',body:'밤숲의 반딧불이가 한 방향으로 모여 작은 길을 만들었어요.',eligibility:s=>s.monthsCompleted>=2&&s.personality.curiosity>=52,choices:[{id:'venture',label:'빛을 따라 걸어간다',statDelta:{magic:2,affection:2},personalityDelta:{curiosity:3,courage:1}},{id:'remember',label:'이 풍경을 오래 기억한다',statDelta:{stress:-4},personalityDelta:{calmness:3}}]},
{id:'training_bell',title:'새벽의 훈련 종',body:'아직 해가 뜨기 전, 오래된 훈련장의 종소리가 한 번 울렸어요.',eligibility:s=>s.monthsCompleted>=4&&(s.mastery.hunt.xp>=5||s.mastery.magic.xp>=5),choices:[{id:'answer',label:'루나와 훈련장으로 간다',statDelta:{strength:3,magic:2,fatigue:4},personalityDelta:{courage:3}},{id:'pace',label:'오늘의 리듬을 먼저 살핀다',statDelta:{fatigue:-3},personalityDelta:{calmness:3}}]},
{id:'winter_letter',title:'겨울에 도착한 편지',body:'이름 없는 편지에는 루나가 성장해 온 모습을 지켜봤다는 짧은 문장이 적혀 있어요.',eligibility:s=>s.monthsCompleted>=8&&s.eventHistory.length>=3,choices:[{id:'cherish',label:'추억 상자에 간직한다',statDelta:{affection:4},personalityDelta:{kindness:2,calmness:2}},{id:'wonder',label:'보낸 사람을 상상해본다',statDelta:{intelligence:2},personalityDelta:{curiosity:3}}]},
{id:'guardian_dream',title:'수호령의 꿈',body:'루나는 꿈속에서 지금까지 걸어온 길과 아직 선택하지 않은 미래를 마주했어요.',eligibility:s=>s.monthsCompleted>=10&&s.memories.length>=4,choices:[{id:'together',label:'함께 걸어온 길을 선택한다',statDelta:{affection:5,morality:2},personalityDelta:{kindness:2}},{id:'future',label:'새로운 미래를 향해 달린다',statDelta:{magic:2,strength:2},personalityDelta:{courage:2,curiosity:2}}]}
];
export function eligibleEvents(state:StoryInput){const view=eventView(state),history=view.eventHistory;return STORY_EVENTS.filter(e=>e.eligibility(view)&&!history.includes(e.id))}
export function selectMonthlyEvent(state:StoryInput){const eligible=eligibleEvents(state);if(!eligible.length)return null;return eligible[(state.year*17+state.month*7+state.personality.curiosity+state.personality.courage)%eligible.length]}
export function applyEventChoice(state:StoryInput,eventId:StoryEventId,choiceId:string):StoryInput{const view=eventView(state),history=view.eventHistory;if(history.includes(eventId))return state;const event=STORY_EVENTS.find(e=>e.id===eventId),choice=event?.choices.find(c=>c.id===choiceId);if(!event||!choice||!event.eligibility(view))return state;const stats={...state.stats};(Object.keys(choice.statDelta??{}) as(keyof Stats)[]).forEach(k=>stats[k]=clamp(stats[k]+(choice.statDelta?.[k]??0)));const personality={...state.personality};(Object.keys(choice.personalityDelta??{}) as PersonalityKey[]).forEach(k=>personality[k]=clamp(personality[k]+(choice.personalityDelta?.[k]??0)));return{...state,stats,personality,gold:Math.max(0,state.gold+(choice.goldDelta??0)),eventHistory:[...history,eventId],activeEventId:undefined}}
