import{describe,expect,it}from'vitest';import{createBattle,playCard,drawHand,battleScore,BATTLE_CARDS,BATTLE_ENEMY,type BattleState}from'./battle';
const fixedRandom=(...values:number[])=>{let i=0;return()=>values[Math.min(i++,values.length-1)]};
describe('battle deck',()=>{
 it('draws the requested hand size from the four unique cards',()=>{const hand=drawHand(fixedRandom(0,.5,.99),3);expect(hand).toHaveLength(3);expect(new Set(hand).size).toBe(3);hand.forEach(id=>expect(BATTLE_CARDS.some(c=>c.id===id)).toBe(true))});
});
describe('battle turn resolution',()=>{
 it('starts with full HP on both sides and a drawn hand',()=>{const b=createBattle(BATTLE_ENEMY,400,8,fixedRandom(0,.3,.6));expect(b.playerHp).toBe(400);expect(b.enemyHp).toBe(BATTLE_ENEMY.maxHp);expect(b.hand).toHaveLength(3);expect(b.finished).toBe(false)});
 it('fireball damages the enemy and the enemy counterattacks the same turn',()=>{const b=createBattle(BATTLE_ENEMY,400,8,fixedRandom(0,.3,.6));const next=playCard(b,'fireball',0,BATTLE_ENEMY,fixedRandom(.1,.4,.7));expect(next.enemyHp).toBeLessThan(b.enemyHp);expect(next.playerHp).toBeLessThan(b.playerHp);expect(next.turn).toBe(2)});
 it('ignores a card that was not actually in hand',()=>{const b={...createBattle(BATTLE_ENEMY,400,8),hand:['heal','shield','focus'] as const};const next=playCard(b as unknown as BattleState,'fireball',0);expect(next).toBe(b)});
 it('shield roughly quarters the incoming damage compared to not blocking',()=>{const b=createBattle(BATTLE_ENEMY,400,8,fixedRandom(0,.3,.6));const shielded=playCard(b,'shield',0,BATTLE_ENEMY,fixedRandom(.1));const bare=playCard({...b,hand:['fireball','heal','focus']},'focus',0,BATTLE_ENEMY,fixedRandom(.1));const shieldedDamage=b.playerHp-shielded.playerHp,bareDamage=b.playerHp-bare.playerHp;expect(shieldedDamage).toBeLessThan(bareDamage/2)});
 it('focus boosts the next fireball but not the focus turn itself',()=>{const b=createBattle(BATTLE_ENEMY,400,8,fixedRandom(0,.3,.6));const focused=playCard(b,'focus',0,BATTLE_ENEMY,fixedRandom(.1));expect(focused.focused).toBe(true);const boosted=playCard({...focused,hand:['fireball','heal','shield']},'fireball',0,BATTLE_ENEMY,fixedRandom(.1));const plain=playCard({...b,focused:false,hand:['fireball','heal','shield']},'fireball',0,BATTLE_ENEMY,fixedRandom(.1));const boostedDamage=b.enemyHp-boosted.enemyHp,plainDamage=b.enemyHp-plain.enemyHp;expect(boostedDamage).toBeGreaterThan(plainDamage);expect(boosted.focused).toBe(false)});
 it('ends in a WIN once enemy HP is fully depleted',()=>{let b=createBattle({...BATTLE_ENEMY,maxHp:50},400,20,fixedRandom(0,.3,.6));b=playCard(b,'fireball',1,{...BATTLE_ENEMY,maxHp:50});expect(b.finished).toBe(true);expect(b.outcome).toBe('WIN');expect(b.enemyHp).toBe(0)});
 it('ends in a LOSE once player HP is fully depleted',()=>{let b=createBattle({...BATTLE_ENEMY,baseAttack:9999},10,20,fixedRandom(0,.3,.6));b=playCard(b,'focus',0,{...BATTLE_ENEMY,baseAttack:9999});expect(b.finished).toBe(true);expect(b.outcome).toBe('LOSE');expect(b.playerHp).toBe(0)});
 it('ends the fight once the turn limit is exceeded without a knockout',()=>{let b:BattleState={...createBattle(BATTLE_ENEMY,4000,1,fixedRandom(0,.3,.6)),hand:['shield','heal','focus']};b=playCard(b,'shield',0,BATTLE_ENEMY,fixedRandom(.1));expect(b.finished).toBe(true);expect(['LOSE','DRAW']).toContain(b.outcome)});
});
describe('battle scoring',()=>{
 it('scores a fast WIN with high remaining HP higher than a slow WIN',()=>{const fast:BattleState={playerHp:380,playerMaxHp:400,enemyHp:0,enemyMaxHp:800,enemyName:'x',focused:false,turn:2,maxTurns:8,hand:[],log:[],finished:true,outcome:'WIN'};const slow:BattleState={...fast,turn:8,playerHp:40};expect(battleScore(fast)).toBeGreaterThan(battleScore(slow))});
 it('scores any LOSE lower than any WIN',()=>{const win:BattleState={playerHp:100,playerMaxHp:400,enemyHp:0,enemyMaxHp:800,enemyName:'x',focused:false,turn:8,maxTurns:8,hand:[],log:[],finished:true,outcome:'WIN'};const lose:BattleState={...win,outcome:'LOSE',playerHp:0,enemyHp:750};expect(battleScore(lose)).toBeLessThan(battleScore(win))});
 it('gives a DRAW partial credit based on how much enemy HP was chipped away',()=>{const barelyDamaged:BattleState={playerHp:50,playerMaxHp:400,enemyHp:750,enemyMaxHp:800,enemyName:'x',focused:false,turn:9,maxTurns:8,hand:[],log:[],finished:true,outcome:'DRAW'};const heavilyDamaged:BattleState={...barelyDamaged,enemyHp:100};expect(battleScore(heavilyDamaged)).toBeGreaterThan(battleScore(barelyDamaged))});
});
