import {describe,expect,it} from 'vitest';
import type {LivingRegionProgress} from './living-region-state';
import {herbHillsExploration} from './herb-hills-world';
const progress=(phase:LivingRegionProgress['phase'],completedInteractions:string[]=[]):LivingRegionProgress=>({phase,discoveries:[],completedInteractions});
const context={personality:{courage:4,kindness:4,curiosity:4,calmness:4},affection:20,worldFacts:[] as string[],inheritedWorldFacts:[] as string[]};
describe('V16 Herb Hills authored region',()=>{
 it('meets the living-region completeness contract',()=>{const x=herbHillsExploration(progress('active'),context);expect(x.world.width).toBeGreaterThan(844);expect(x.world.height).toBeGreaterThan(844);expect(x.world.obstacles.length).toBeGreaterThanOrEqual(6);expect(x.world.interactables.filter(i=>i.id.startsWith('herb-npc-')).length).toBe(3);expect(Object.keys(x.discoveryByInteraction)).toHaveLength(3);expect(x.world.interactables.some(i=>i.kind==='exit')).toBe(true);for(const item of x.world.interactables){if(item.storyFrameId)expect(x.storyFrames[item.storyFrameId]).toBeDefined();if(item.artSrc)expect(item.artSrc).toContain('/assets/exploration/herb-hills/');}});
 it('requires the authored gathering chain before delivery',()=>{const x=herbHillsExploration(progress('mainQuestInProgress',['herb-mira-request']),context);expect(x.questStartInteractionId).toBe('herb-mira-request');expect(x.questResolveInteractionId).toBe('herb-delivery-basket');expect(x.world.interactables.find(i=>i.id==='herb-rare-bloom')?.requiresCompleted).toEqual(['herb-mint-patch','herb-sunleaf-patch']);expect(x.world.interactables.find(i=>i.id==='herb-delivery-basket')?.requiresCompleted).toContain('herb-rare-bloom');});
 it('shows a persistent improved gathering state and revisit after resolution',()=>{const active=herbHillsExploration(progress('active'),context);const resolved=herbHillsExploration(progress('mainQuestResolved'),context);const post=herbHillsExploration(progress('postResolution'),context);expect(active.world.interactables.some(i=>i.id==='herb-restored-rack')).toBe(false);expect(resolved.world.interactables.some(i=>i.id==='herb-restored-rack')).toBe(true);expect(resolved.world.layers.some(l=>l.id==='restored')).toBe(true);expect(post.world.objective).toContain('다시');});
 it('changes local dialogue for personality, bond and world history',()=>{const kind=herbHillsExploration(progress('active'),{...context,personality:{...context.personality,kindness:12}});const experienced=herbHillsExploration(progress('active'),{...context,inheritedWorldFacts:['old_route_memory']});const bonded=herbHillsExploration(progress('mainQuestResolved'),{...context,affection:60});expect(kind.storyFrames['herb-mira'].text).toContain('조심히');expect(experienced.storyFrames['herb-jun'].text).toContain('멀리');expect(bonded.storyFrames['herb-mira'].text).toContain('루나');});
});
