export type Screen='hub'|'schedule'|'training'|'dialogue'|'result';
export type ActivityId='hunt'|'magic'|'rest'|'herb';
export type Condition='energetic'|'normal'|'focused'|'tired';
export type TrainingQuality='NORMAL'|'GOOD'|'GREAT'|'PERFECT';
export type PersonalityKey='courage'|'kindness'|'curiosity'|'calmness';
export type MemoryId='first_training'|'first_perfect'|'first_hug'|'first_snack'|'first_s_grade'|'first_month_complete';
export interface Stats{strength:number;intelligence:number;magic:number;morality:number;affection:number;stress:number;fatigue:number}
export type Personality=Record<PersonalityKey,number>;
export type Mastery=Record<ActivityId,{xp:number}>;
export interface MemoryEntry{id:MemoryId;year:number;month:number}
export interface GrowthReport{quality:TrainingQuality;grade:'S'|'A'|'B'|'C';mostImprovedStat:keyof Stats;masteryGains:Record<ActivityId,number>;personalityChanges:Partial<Record<PersonalityKey,number>>;newMemory?:MemoryId;nextCondition:Condition;goldReward:number}
interface PendingGrowth{quality:TrainingQuality;grade:'S'|'A'|'B'|'C';statsBefore:Stats;masteryGains:Record<ActivityId,number>;personalityBefore:Personality;memoryCountBefore:number}
export interface GameState{screen:Screen;year:number;month:number;week:number;gold:number;gems:number;schedule:ActivityId[];stats:Stats;combo:number;trainingScore:number;lastChoice?:string;condition:Condition;mastery:Mastery;personality:Personality;memories:MemoryEntry[];lastGrowthReport:GrowthReport|null;pendingGrowth?:PendingGrowth}
export const activities:Record<ActivityId,{name:string;icon:string;effect:Partial<Stats>}>= {hunt:{name:'사냥 훈련',icon:'sword',effect:{strength:6,fatigue:9,stress:4}},magic:{name:'마법 수업',icon:'spark',effect:{magic:7,intelligence:3,fatigue:7}},rest:{name:'포근한 휴식',icon:'moon',effect:{stress:-16,fatigue:-20,affection:2}},herb:{name:'약초 채집',icon:'leaf',effect:{intelligence:2,fatigue:5}}};
const emptyMastery=():Mastery=>({hunt:{xp:0},magic:{xp:0},rest:{xp:0},herb:{xp:0}});
const defaultPersonality=():Personality=>({courage:50,kindness:50,curiosity:50,calmness:50});
const emptyGains=():Record<ActivityId,number>=>({hunt:0,magic:0,rest:0,herb:0});
export const initialState:GameState={screen:'hub',year:1,month:4,week:2,gold:5000,gems:220,schedule:['hunt','magic','rest','herb'],combo:0,trainingScore:0,stats:{strength:28,intelligence:34,magic:42,morality:61,affection:72,stress:24,fatigue:18},condition:'normal',mastery:emptyMastery(),personality:defaultPersonality(),memories:[],lastGrowthReport:null};
const clamp=(v:number)=>Math.max(0,Math.min(100,v));
const validActivities:ActivityId[]=['hunt','magic','rest','herb'];
const validConditions:Condition[]=['energetic','normal','focused','tired'];
export function applyActivity(stats:Stats,id:ActivityId):Stats{const next={...stats};for(const[key,value]of Object.entries(activities[id].effect)){const k=key as keyof Stats;next[k]=clamp(next[k]+(value??0));}return next}
export function trainingGrade(score:number):'S'|'A'|'B'|'C'{return score>=900?'S':score>=650?'A':score>=400?'B':'C'}
export function trainingQuality(score:number):TrainingQuality{return score>=900?'PERFECT':score>=650?'GREAT':score>=400?'GOOD':'NORMAL'}
export function conditionScoreMultiplier(c:Condition){return c==='energetic'?1.1:c==='focused'?1.05:c==='tired'?.9:1}
export function masteryLevel(xp:number){return xp>=18?5:xp>=12?4:xp>=7?3:xp>=3?2:1}
export function deriveCondition(s:Stats):Condition{if(s.fatigue>=70)return'tired';if(s.stress<=15&&s.fatigue<=25)return'focused';if(s.fatigue<=15&&s.stress<=30)return'energetic';return'normal'}
function addMemory(state:GameState,id:MemoryId){return state.memories.some(m=>m.id===id)?state:{...state,memories:[...state.memories,{id,year:state.year,month:state.month}]}}
function personalityDeltaForActivity(id:ActivityId):Partial<Personality>{return id==='hunt'?{courage:2}:id==='magic'?{curiosity:2}:id==='rest'?{calmness:2}:{curiosity:1,calmness:1}}
function applyPersonalityDelta(p:Personality,d:Partial<Personality>){const next={...p};(Object.keys(d)as PersonalityKey[]).forEach(k=>next[k]=clamp(next[k]+(d[k]??0)));return next}
function mostImprovedStat(before:Stats,after:Stats):keyof Stats{return(Object.keys(after)as(keyof Stats)[]).reduce((best,k)=>after[k]-before[k]>after[best]-before[best]?k:best,'strength')}
const safeNumber=(v:unknown,f:number)=>typeof v==='number'&&Number.isFinite(v)?v:f;
export function hydrateGameState(raw:string|null):GameState{if(!raw)return initialState;try{const parsed=JSON.parse(raw)as Partial<GameState>;if(!parsed||typeof parsed!=='object')return initialState;const stats={...initialState.stats};if(parsed.stats&&typeof parsed.stats==='object')(Object.keys(stats)as(keyof Stats)[]).forEach(k=>stats[k]=clamp(safeNumber(parsed.stats?.[k],stats[k])));const mastery=emptyMastery();if(parsed.mastery&&typeof parsed.mastery==='object')validActivities.forEach(id=>mastery[id]={xp:Math.max(0,safeNumber(parsed.mastery?.[id]?.xp,0))});const personality=defaultPersonality();if(parsed.personality&&typeof parsed.personality==='object')(Object.keys(personality)as PersonalityKey[]).forEach(k=>personality[k]=clamp(safeNumber(parsed.personality?.[k],50)));const memories=Array.isArray(parsed.memories)?parsed.memories.filter((e):e is MemoryEntry=>Boolean(e&&typeof e==='object'&&['first_training','first_perfect','first_hug','first_snack','first_s_grade','first_month_complete'].includes((e as MemoryEntry).id))):[];const schedule=Array.isArray(parsed.schedule)&&parsed.schedule.length===4&&parsed.schedule.every(id=>validActivities.includes(id))?parsed.schedule:initialState.schedule;return{...initialState,...parsed,screen:['hub','schedule','training','dialogue','result'].includes(parsed.screen??'')?parsed.screen!:initialState.screen,year:safeNumber(parsed.year,initialState.year),month:safeNumber(parsed.month,initialState.month),week:Math.max(1,Math.min(4,safeNumber(parsed.week,initialState.week))),gold:Math.max(0,safeNumber(parsed.gold,initialState.gold)),gems:Math.max(0,safeNumber(parsed.gems,initialState.gems)),combo:Math.max(0,safeNumber(parsed.combo,0)),trainingScore:Math.max(0,safeNumber(parsed.trainingScore,0)),stats,schedule,mastery,personality,memories,condition:validConditions.includes(parsed.condition as Condition)?parsed.condition as Condition:'normal',lastGrowthReport:parsed.lastGrowthReport&&typeof parsed.lastGrowthReport==='object'?parsed.lastGrowthReport:null}}catch{return initialState}}
export function applyDialogueChoice(state:GameState,choice:'hug'|'scold'|'snack'):GameState{const stats={...state.stats};if(choice==='hug'){stats.stress=clamp(stats.stress-20);stats.affection=clamp(stats.affection+10);stats.morality=clamp(stats.morality+2)}if(choice==='scold'){stats.morality=clamp(stats.morality+5);stats.stress=clamp(stats.stress+15)}if(choice==='snack'){stats.stress=clamp(stats.stress-30);stats.affection=clamp(stats.affection+4)}const delta:Partial<Personality>=choice==='hug'?{kindness:4}:choice==='snack'?{kindness:2}:{courage:2,calmness:-1};let next:GameState={...state,stats,personality:applyPersonalityDelta(state.personality,delta),gold:choice==='snack'?Math.max(0,state.gold-100):state.gold,lastChoice:choice,screen:'result'};if(choice==='hug')next=addMemory(next,'first_hug');if(choice==='snack')next=addMemory(next,'first_snack');const p=state.pendingGrowth;if(p){const newMemory=next.memories.slice(p.memoryCountBefore)[0]?.id;const personalityChanges:Partial<Record<PersonalityKey,number>>={};(Object.keys(next.personality)as PersonalityKey[]).forEach(k=>{const d=next.personality[k]-p.personalityBefore[k];if(d)personalityChanges[k]=d});next={...next,lastGrowthReport:{quality:p.quality,grade:p.grade,mostImprovedStat:mostImprovedStat(p.statsBefore,next.stats),masteryGains:p.masteryGains,personalityChanges,newMemory,nextCondition:deriveCondition(next.stats),goldReward:350}}}return next}
export type Action={type:'GO';screen:Screen}|{type:'SET_SCHEDULE';index:number;activity:ActivityId}|{type:'AUTO_SCHEDULE'}|{type:'TRAIN';kind:'attack'|'dodge'|'charge';accuracy:number}|{type:'FINISH_TRAINING'}|{type:'CHOOSE';choice:'hug'|'scold'|'snack'}|{type:'NEXT_MONTH'}|{type:'RESET'};
export function reducer(state:GameState,action:Action):GameState{switch(action.type){case'GO':return{...state,screen:action.screen};case'SET_SCHEDULE':{const schedule=[...state.schedule];schedule[action.index]=action.activity;return{...state,schedule}}case'AUTO_SCHEDULE':return{...state,schedule:['hunt','magic','rest','herb']};case'TRAIN':{const base=action.accuracy*(action.kind==='attack'?140:action.kind==='dodge'?110:80);return{...state,combo:action.accuracy>.55?state.combo+1:0,trainingScore:state.trainingScore+Math.round(base*conditionScoreMultiplier(state.condition))}}case'FINISH_TRAINING':{const id=state.schedule[Math.max(0,Math.min(3,state.week-1))];const quality=trainingQuality(state.trainingScore),grade=trainingGrade(state.trainingScore),gain=1+(quality==='PERFECT'?2:quality==='GREAT'?1:0);let stats=applyActivity(state.stats,id);if(id==='hunt')stats.strength=clamp(stats.strength+(grade==='S'?8:grade==='A'?5:2));const personality=applyPersonalityDelta(state.personality,personalityDeltaForActivity(id));const mastery={...state.mastery,[id]:{xp:state.mastery[id].xp+gain}};const previous=state.pendingGrowth;const masteryGains=previous?{...previous.masteryGains}:emptyGains();masteryGains[id]+=gain;const pendingGrowth:PendingGrowth={quality,grade,statsBefore:previous?.statsBefore??{...state.stats},masteryGains,personalityBefore:previous?.personalityBefore??{...state.personality},memoryCountBefore:previous?.memoryCountBefore??state.memories.length};let next:GameState={...state,stats,personality,mastery,pendingGrowth,combo:0,trainingScore:0,week:state.week<4?state.week+1:4,screen:state.week<4?'training':'dialogue'};next=addMemory(next,'first_training');if(quality==='PERFECT')next=addMemory(next,'first_perfect');if(grade==='S')next=addMemory(next,'first_s_grade');return next}case'CHOOSE':return applyDialogueChoice(state,action.choice);case'NEXT_MONTH':{const month=state.month===12?1:state.month+1,year=state.month===12?state.year+1:state.year;let next=addMemory(state,'first_month_complete');return{...next,month,year,week:1,screen:'hub',combo:0,trainingScore:0,gold:next.gold+350,condition:deriveCondition(next.stats),pendingGrowth:undefined}}case'RESET':return initialState;default:return state}}
