import { describe, expect, it } from 'vitest';
import { STORY_EVENTS } from './game/events';
import { applyActivity, applyDialogueChoice, conditionScoreMultiplier, hydrateGameState, initialState, masteryLevel, reducer, trainingGrade, trainingQuality, type GameState } from './game';
function resolveEventIfPresent(state:GameState){if(state.screen!=='event'||!state.activeEventId)return state;const event=STORY_EVENTS.find(item=>item.id===state.activeEventId)!;return reducer(state,{type:'EVENT_CHOICE',eventId:event.id,choiceId:event.choices[0].id})}
function finishMonth(state:GameState){state={...state,screen:'training',week:1};for(let week=1;week<=4;week++)state=reducer({...state,trainingScore:700},{type:'FINISH_TRAINING'});state=reducer(state,{type:'CHOOSE',choice:'hug'});state=resolveEventIfPresent(state);return reducer(state,{type:'NEXT_MONTH'})}
describe('game engine',()=>{
it('applies activity effects without exceeding stat bounds',()=>{const next=applyActivity({...initialState.stats,stress:5,fatigue:4},'rest');expect(next.stress).toBe(0);expect(next.fatigue).toBe(0);expect(next.affection).toBe(74)});
it('calculates training grades and positive quality boundaries',()=>{expect(trainingGrade(920)).toBe('S');expect(trainingGrade(700)).toBe('A');expect(trainingQuality(899)).toBe('GREAT');expect(trainingQuality(900)).toBe('PERFECT');expect(trainingQuality(399)).toBe('NORMAL');expect(trainingQuality(400)).toBe('GOOD')});
it('hydrates legacy saves with current defaults and preserves progress',()=>{const hydrated=hydrateGameState(JSON.stringify({...initialState,gold:7777,condition:undefined,mastery:undefined,eventHistory:undefined,endingCollection:undefined,claimedMilestones:undefined}));expect(hydrated.gold).toBe(7777);expect(hydrated.condition).toBe('normal');expect(hydrated.mastery.hunt.xp).toBe(0);expect(hydrated.endingCollection).toEqual([]);expect(hydrated.claimedMilestones).toEqual([])});
it('falls back safely for malformed saves',()=>{expect(hydrateGameState('{bad json')).toEqual(initialState)});
it('normalizes corrupt calendar, schedule, resources and duplicate collections',()=>{const hydrated=hydrateGameState(JSON.stringify({...initialState,month:99,week:-4,gold:-2,schedule:['bad'],endingCollection:['guardian','guardian','bad'],claimedMilestones:['half-year','half-year','bad']}));expect(hydrated.month).toBe(12);expect(hydrated.week).toBe(1);expect(hydrated.gold).toBe(0);expect(hydrated.schedule).toEqual(initialState.schedule);expect(hydrated.endingCollection).toEqual(['guardian']);expect(hydrated.claimedMilestones).toEqual(['half-year'])});
it('uses deterministic condition modifiers and mastery levels',()=>{expect(conditionScoreMultiplier('energetic')).toBe(1.1);expect(conditionScoreMultiplier('tired')).toBeLessThan(1);expect(masteryLevel(18)).toBe(5)});
it('applies dialogue personality and memory effects once before optional event',()=>{const once=applyDialogueChoice(initialState,'hug'),twice=applyDialogueChoice({...once,screen:'dialogue'},'hug');expect(once.stats.affection).toBe(82);expect(once.memories.filter(m=>m.id==='first_hug')).toHaveLength(1);expect(twice.memories.filter(m=>m.id==='first_hug')).toHaveLength(1)});
it('finishes final training week with mastery, memories and report deltas',()=>{const trained=reducer({...initialState,week:4,trainingScore:920},{type:'FINISH_TRAINING'});expect(trained.screen).toBe('dialogue');expect(trained.mastery.herb.xp).toBeGreaterThan(0);const result=reducer(trained,{type:'CHOOSE',choice:'snack'});expect(result.lastGrowthReport?.quality).toBe('PERFECT')});
it('runs canonical monthly loop through optional event and returns home',()=>{let state:GameState={...initialState,screen:'schedule',week:1};state=reducer(state,{type:'GO',screen:'training'});for(let week=1;week<=4;week++)state=reducer({...state,trainingScore:920},{type:'FINISH_TRAINING'});state=reducer(state,{type:'CHOOSE',choice:'hug'});state=resolveEventIfPresent(state);state=reducer(state,{type:'NEXT_MONTH'});expect(state.screen).toBe('hub');expect(state.week).toBe(1);expect(state.month).toBe(5)});
it('runs twelve complete months with bounded state and exactly one ending',()=>{let state:GameState={...initialState,month:1,week:1,monthsCompleted:0};for(let month=0;month<12;month++){state=finishMonth(state);expect(state.month).toBeGreaterThanOrEqual(1);expect(state.month).toBeLessThanOrEqual(12);expect(state.gold).toBeGreaterThanOrEqual(0);for(const value of Object.values(state.stats))expect(value).toBeGreaterThanOrEqual(0);for(const value of Object.values(state.stats))expect(value).toBeLessThanOrEqual(100);expect(new Set(state.memories.map(m=>m.id)).size).toBe(state.memories.length)}expect(state.screen).toBe('ending');expect(state.monthsCompleted).toBe(12);expect(state.resolvedEnding).toBeTruthy();expect(state.endingCollection).toContain(state.resolvedEnding!);expect(state.claimedMilestones).toEqual(['first-quarter','half-year','final-quarter','final-month'])});
it('preserves discovered endings when a new run starts',()=>{const ended=reducer({...initialState,screen:'result',monthsCompleted:11},{type:'NEXT_MONTH'});const restarted=reducer(ended,{type:'NEW_RUN'});expect(restarted.screen).toBe('hub');expect(restarted.monthsCompleted).toBe(0);expect(restarted.endingCollection).toEqual(ended.endingCollection);expect(restarted.resolvedEnding).toBeUndefined()});
it('keeps schedule edits inside four visible weeks',()=>{expect(reducer(initialState,{type:'SET_SCHEDULE',index:9,activity:'rest'}).schedule).toEqual(initialState.schedule)});
it('does not charge snack when gold is insufficient',()=>{const next=applyDialogueChoice({...initialState,gold:50},'snack');expect(next.gold).toBe(50);expect(next.lastChoice).not.toBe('snack')});
it('hydrates duplicate memories only once',()=>{const hydrated=hydrateGameState(JSON.stringify({...initialState,memories:[{id:'first_training',year:1,month:4},{id:'first_training',year:1,month:4}]}));expect(hydrated.memories).toHaveLength(1)});
});
