export * from './game-astral-rift-base';

import * as Base from './game-astral-rift-base';
import { astralRiftDefinitions,astralRiftPower,canEnterAstralRift,resolveAstralRift,updateAstralRiftRecord,type AstralRiftId,type AstralRiftIntensity,type AstralRiftRecord,type AstralRiftRecordMap } from './astral-rift';
import { astralRiftRelics,resolveAstralRiftRelicPurchase,type AstralRiftRelicId } from './astral-rift-relics';
import { advanceAstralRiftWeekly,astralRiftWeeklyDirectives,astralRiftWeeklyKey,type AstralRiftDirectiveId } from './astral-rift-weekly';
import { astralRiftHonors,newlyEarnedAstralRiftHonors,type AstralRiftHonorId } from './astral-rift-honors';
import { astralRiftClearCount,canEnterConvergence,celestialGuardianDefinitions,convergencePower,resolveConvergence,updateConvergenceRecord,type CelestialGuardianId,type ConvergenceIntensity,type ConvergenceRecord,type ConvergenceRecordMap } from './celestial-convergence';
import { guardianBoons,resolveGuardianBoonPurchase,sanitizeGuardianBoons,type GuardianBoonId } from './guardian-boons';
import { advanceConvergenceWeekly,convergenceWeeklyDirectives,convergenceWeeklyKey,type ConvergenceDirectiveId } from './convergence-weekly';
import { convergenceHonors,newlyEarnedConvergenceHonors,type ConvergenceHonorId } from './convergence-honors';
import { callingMasteryLevel } from './calling-mastery';
import { celestialAscensionProgress } from './celestial-ascension';
import { sanctuaryGrandProgress } from './sanctuary-grand-milestones';
import { legacyPathEffects,legacyScore,type SanctuaryLegacyPathId } from './sanctuary-legacy';
import { claimableLegacyMilestones,legacyRewardTotal,sanctuaryLegacyMilestones,type LegacyMilestoneProgress,type SanctuaryLegacyMilestoneId } from './sanctuary-legacy-milestones';

export type GameState = Base.GameState & {
  astralRiftRecords:AstralRiftRecordMap; astralRiftEchoes:number; purchasedAstralRiftRelics:AstralRiftRelicId[]; astralRiftWeeklyKey:string|null; astralRiftWeeklyProgress:Record<string,number>; rewardedAstralRiftDirectives:string[]; claimedAstralRiftHonors:AstralRiftHonorId[];
  celestialConvergenceRecords:ConvergenceRecordMap; guardianSigils:number; purchasedGuardianBoons:GuardianBoonId[]; convergenceWeeklyKey:string|null; convergenceWeeklyProgress:Record<string,number>; rewardedConvergenceDirectives:string[]; claimedConvergenceHonors:ConvergenceHonorId[];
  sanctuaryLegacyPath:SanctuaryLegacyPathId|null; claimedSanctuaryLegacyMilestones:SanctuaryLegacyMilestoneId[];
};
export type Action = Base.Action | {type:'CLEAR_ASTRAL_RIFT';riftId:AstralRiftId;intensity:AstralRiftIntensity}|{type:'PURCHASE_ASTRAL_RIFT_RELIC';relicId:AstralRiftRelicId}|{type:'CLEAR_CELESTIAL_CONVERGENCE';guardianId:CelestialGuardianId;intensity:ConvergenceIntensity}|{type:'PURCHASE_GUARDIAN_BOON';boonId:GuardianBoonId}|{type:'SELECT_SANCTUARY_LEGACY_PATH';path:SanctuaryLegacyPathId|null}|{type:'CLAIM_SANCTUARY_LEGACY_REWARDS'};
export const initialState:GameState={...Base.initialState,astralRiftRecords:{},astralRiftEchoes:0,purchasedAstralRiftRelics:[],astralRiftWeeklyKey:null,astralRiftWeeklyProgress:{},rewardedAstralRiftDirectives:[],claimedAstralRiftHonors:[],celestialConvergenceRecords:{},guardianSigils:0,purchasedGuardianBoons:[],convergenceWeeklyKey:null,convergenceWeeklyProgress:{},rewardedConvergenceDirectives:[],claimedConvergenceHonors:[],sanctuaryLegacyPath:null,claimedSanctuaryLegacyMilestones:[]};
const isRecord=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v); const safeInt=(v:unknown)=>typeof v==='number'&&Number.isFinite(v)?Math.max(0,Math.floor(v)):0;
const validRiftIds=astralRiftDefinitions.map(i=>i.id),validRelicIds=astralRiftRelics.map(i=>i.id),validRiftHonorIds=astralRiftHonors.map(i=>i.id),validGuardianIds=celestialGuardianDefinitions.map(i=>i.id),validConvergenceHonorIds=convergenceHonors.map(i=>i.id),validLegacyMilestoneIds=sanctuaryLegacyMilestones.map(i=>i.id);
const riftDirectiveTargets:Record<AstralRiftDirectiveId,number>={rift_clear:2,high_grade:1,featured_rift:1},convergenceDirectiveTargets:Record<ConvergenceDirectiveId,number>={convergence_clear:2,high_grade:1,featured_guardian:1};
function sanitizeRiftRecords(raw:unknown):AstralRiftRecordMap{if(!isRecord(raw))return{};const out:AstralRiftRecordMap={};for(const[k,v]of Object.entries(raw)){const[id,n]=k.split(':');if(!validRiftIds.includes(id as AstralRiftId)||!['1','2','3'].includes(n)||!isRecord(v)||!['B','A','S'].includes(String(v.grade)))continue;const c=safeInt(v.clearCount);if(c<1)continue;out[k]={grade:v.grade as AstralRiftRecord['grade'],bestPower:safeInt(v.bestPower),clearCount:c};}return out;}
function sanitizeConvergenceRecords(raw:unknown):ConvergenceRecordMap{if(!isRecord(raw))return{};const out:ConvergenceRecordMap={};for(const[k,v]of Object.entries(raw)){const[id,n]=k.split(':');if(!validGuardianIds.includes(id as CelestialGuardianId)||!['1','2','3'].includes(n)||!isRecord(v)||!['B','A','S'].includes(String(v.grade)))continue;const c=safeInt(v.clearCount);if(c<1)continue;out[k]={grade:v.grade as ConvergenceRecord['grade'],bestPower:safeInt(v.bestPower),clearCount:c};}return out;}
const sanitizeRelics=(raw:unknown):AstralRiftRelicId[]=>!Array.isArray(raw)?[]:validRelicIds.filter(id=>raw.includes(id));
function sanitizeWeeklyKey(raw:unknown){if(typeof raw!=='string')return null;const m=/^(\d+)-(\d+)-([1-4])$/.exec(raw);if(!m)return null;const y=Number(m[1]),mo=Number(m[2]);return y>=1&&mo>=1&&mo<=12?`${y}-${mo}-${m[3]}`:null;}
function sanitizeProgress(raw:unknown,targets:Record<string,number>){if(!isRecord(raw))return{};const out:Record<string,number>={};for(const[id,target]of Object.entries(targets))if(id in raw)out[id]=Math.min(target,safeInt(raw[id]));return out;}
const sanitizeRewardedDirectives=(raw:unknown,p:RegExp):string[]=>!Array.isArray(raw)?[]:[...new Set(raw.filter((v):v is string=>typeof v==='string'&&p.test(v)))];
const sanitizeRiftHonors=(raw:unknown):AstralRiftHonorId[]=>!Array.isArray(raw)?[]:validRiftHonorIds.filter(id=>raw.includes(id)); const sanitizeConvergenceHonors=(raw:unknown):ConvergenceHonorId[]=>!Array.isArray(raw)?[]:validConvergenceHonorIds.filter(id=>raw.includes(id));
const sanitizeLegacyPath=(raw:unknown):SanctuaryLegacyPathId|null=>raw==='mentor'||raw==='wayfarer'||raw==='keeper'?raw:null;
const sanitizeLegacyMilestones=(raw:unknown):SanctuaryLegacyMilestoneId[]=>!Array.isArray(raw)?[]:validLegacyMilestoneIds.filter(id=>raw.includes(id));
export function hydrateGameState(raw:unknown):GameState{const s=isRecord(raw)?raw:{};return{...Base.hydrateGameState(raw),astralRiftRecords:sanitizeRiftRecords(s.astralRiftRecords),astralRiftEchoes:safeInt(s.astralRiftEchoes),purchasedAstralRiftRelics:sanitizeRelics(s.purchasedAstralRiftRelics),astralRiftWeeklyKey:sanitizeWeeklyKey(s.astralRiftWeeklyKey),astralRiftWeeklyProgress:sanitizeProgress(s.astralRiftWeeklyProgress,riftDirectiveTargets),rewardedAstralRiftDirectives:sanitizeRewardedDirectives(s.rewardedAstralRiftDirectives,/^\d+-(?:[1-9]|1[0-2])-[1-4]:(rift_clear|high_grade|featured_rift)$/),claimedAstralRiftHonors:sanitizeRiftHonors(s.claimedAstralRiftHonors),celestialConvergenceRecords:sanitizeConvergenceRecords(s.celestialConvergenceRecords),guardianSigils:safeInt(s.guardianSigils),purchasedGuardianBoons:sanitizeGuardianBoons(s.purchasedGuardianBoons),convergenceWeeklyKey:sanitizeWeeklyKey(s.convergenceWeeklyKey),convergenceWeeklyProgress:sanitizeProgress(s.convergenceWeeklyProgress,convergenceDirectiveTargets),rewardedConvergenceDirectives:sanitizeRewardedDirectives(s.rewardedConvergenceDirectives,/^\d+-(?:[1-9]|1[0-2])-[1-4]:(convergence_clear|high_grade|featured_guardian)$/),claimedConvergenceHonors:sanitizeConvergenceHonors(s.claimedConvergenceHonors),sanctuaryLegacyPath:sanitizeLegacyPath(s.sanctuaryLegacyPath),claimedSanctuaryLegacyMilestones:sanitizeLegacyMilestones(s.claimedSanctuaryLegacyMilestones)};}
function sanctuaryScore(state:Base.GameState){return sanctuaryGrandProgress({levels:state.sanctuaryLevels,specializationCount:Object.keys(state.sanctuarySpecializations??{}).length,masterworkCount:state.sanctuaryMasterworks?.length??0,prestige:state.sanctuaryPrestige??0});}
function ascensionScore(state:Base.GameState){return celestialAscensionProgress({trialRecords:state.astralTrialRecords??[],blessingCount:state.purchasedAstralBlessings?.length??0,constellationCount:state.sanctuaryConstellations?.length??0,sanctuaryGrandProgress:sanctuaryScore(state)});}
function currentCallingLevel(state:Base.GameState){return !state.activeCalling?0:callingMasteryLevel(state.callingMastery?.[state.activeCalling]??0);}
function legacyProgress(state:GameState):LegacyMilestoneProgress{const cKeys=Object.keys(state.celestialConvergenceRecords),guardians=new Set(cKeys.map(k=>k.split(':')[0])).size,maxIntensity=cKeys.reduce((m,k)=>Math.max(m,Number(k.split(':')[1])||0),0),riftClears=Object.keys(state.astralRiftRecords).length,grand=sanctuaryScore(state),asc=ascensionScore(state),calling=currentCallingLevel(state),relics=state.purchasedAstralRiftRelics.length,score=legacyScore({convergence:Math.min(1,(guardians/4)*.6+(maxIntensity/3)*.4),boons:Math.min(1,state.purchasedGuardianBoons.length/8),grand:Math.min(1,grand/100),ascension:Math.min(1,asc/100),calling:Math.min(1,calling/4),rifts:Math.min(1,(riftClears/12)*.6+(relics/8)*.4)});return{score,convergenceGuardians:guardians,maxConvergenceIntensity:maxIntensity,boons:state.purchasedGuardianBoons.length,celestialRank:grand>=85,ascension:asc,callingMastery:calling,riftClears,riftRelics:relics};}
function endgameState(s:GameState){return{astralRiftRecords:s.astralRiftRecords,astralRiftEchoes:s.astralRiftEchoes,purchasedAstralRiftRelics:s.purchasedAstralRiftRelics,astralRiftWeeklyKey:s.astralRiftWeeklyKey,astralRiftWeeklyProgress:s.astralRiftWeeklyProgress,rewardedAstralRiftDirectives:s.rewardedAstralRiftDirectives,claimedAstralRiftHonors:s.claimedAstralRiftHonors,celestialConvergenceRecords:s.celestialConvergenceRecords,guardianSigils:s.guardianSigils,purchasedGuardianBoons:s.purchasedGuardianBoons,convergenceWeeklyKey:s.convergenceWeeklyKey,convergenceWeeklyProgress:s.convergenceWeeklyProgress,rewardedConvergenceDirectives:s.rewardedConvergenceDirectives,claimedConvergenceHonors:s.claimedConvergenceHonors,sanctuaryLegacyPath:s.sanctuaryLegacyPath,claimedSanctuaryLegacyMilestones:s.claimedSanctuaryLegacyMilestones};}
export function reducer(state:GameState,action:Action):GameState{
 if(action.type==='RESET')return initialState;
 if(action.type==='SELECT_SANCTUARY_LEGACY_PATH'){if(state.sanctuaryLegacyPath===action.path)return state;return{...state,sanctuaryLegacyPath:action.path};}
 if(action.type==='CLAIM_SANCTUARY_LEGACY_REWARDS'){const items=claimableLegacyMilestones(legacyProgress(state),state.claimedSanctuaryLegacyMilestones);if(!items.length)return state;const r=legacyRewardTotal(items);return{...state,claimedSanctuaryLegacyMilestones:[...state.claimedSanctuaryLegacyMilestones,...items.map(i=>i.id)],gold:state.gold+r.gold,gems:state.gems+r.gems};}
 if(action.type==='PURCHASE_GUARDIAN_BOON'){const r=resolveGuardianBoonPurchase({boonId:action.boonId,sigils:state.guardianSigils,purchased:state.purchasedGuardianBoons});if(!r.accepted)return state;return{...state,guardianSigils:r.sigils,purchasedGuardianBoons:r.purchased,gold:state.gold+r.reward.gold,gems:state.gems+r.reward.gems};}
 if(action.type==='CLEAR_CELESTIAL_CONVERGENCE'){if(!canEnterConvergence({guardianId:action.guardianId,intensity:action.intensity,riftRecords:state.astralRiftRecords,riftRelicCount:state.purchasedAstralRiftRelics.length}))return state;const power=convergencePower({ascensionScore:ascensionScore(state),sanctuaryGrandProgress:sanctuaryScore(state),callingMasteryLevel:currentCallingLevel(state),astralRiftClearCount:astralRiftClearCount(state.astralRiftRecords),riftRelicCount:state.purchasedAstralRiftRelics.length,activeCalling:state.activeCalling,guardianId:action.guardianId});const key=`${action.guardianId}:${action.intensity}`,resolved=resolveConvergence(action.guardianId,action.intensity,power,!state.celestialConvergenceRecords[key]);if(!resolved.success)return state;const records=updateConvergenceRecord(state.celestialConvergenceRecords,action.guardianId,action.intensity,{grade:resolved.grade,power}),weekKey=convergenceWeeklyKey(state.year,state.month,state.week),weekly=advanceConvergenceWeekly({directives:convergenceWeeklyDirectives(state.year,state.month,state.week),progress:state.convergenceWeeklyKey===weekKey?state.convergenceWeeklyProgress:{},rewardedKeys:state.rewardedConvergenceDirectives,weekKey,event:{guardianId:action.guardianId,grade:resolved.grade,success:true}}),earned=newlyEarnedConvergenceHonors(records,state.claimedConvergenceHonors),fx=legacyPathEffects(state.sanctuaryLegacyPath);const journeyKey=`${state.year}-${state.month}`;return{...state,celestialConvergenceRecords:records,guardianSigils:state.guardianSigils+resolved.sigils+weekly.sigils,convergenceWeeklyKey:weekKey,convergenceWeeklyProgress:weekly.progress,rewardedConvergenceDirectives:weekly.rewardedKeys,claimedConvergenceHonors:[...state.claimedConvergenceHonors,...earned.map(i=>i.id)],gold:state.gold+earned.reduce((s,i)=>s+i.reward.gold,0),gems:state.gems+earned.reduce((s,i)=>s+i.reward.gems,0),seasonJourneyScores:{...state.seasonJourneyScores,[journeyKey]:(state.seasonJourneyScores[journeyKey]??0)+fx.convergenceJourney}};}
 if(action.type==='PURCHASE_ASTRAL_RIFT_RELIC'){const r=resolveAstralRiftRelicPurchase({relicId:action.relicId,echoes:state.astralRiftEchoes,purchased:state.purchasedAstralRiftRelics});if(!r.accepted)return state;return{...state,astralRiftEchoes:r.echoes,purchasedAstralRiftRelics:r.purchased};}
 if(action.type==='CLEAR_ASTRAL_RIFT'){const asc=ascensionScore(state);if(!canEnterAstralRift({riftId:action.riftId,intensity:action.intensity,ascensionScore:asc,records:state.astralRiftRecords}))return state;const power=astralRiftPower({ascensionScore:asc,sanctuaryGrandProgress:sanctuaryScore(state),callingMasteryLevel:currentCallingLevel(state),blessingCount:state.purchasedAstralBlessings?.length??0}),key=`${action.riftId}:${action.intensity}`,resolved=resolveAstralRift(action.riftId,action.intensity,power,!state.astralRiftRecords[key]);if(!resolved.success)return state;const records=updateAstralRiftRecord(state.astralRiftRecords,action.riftId,action.intensity,{grade:resolved.grade,power}),weekKey=astralRiftWeeklyKey(state.year,state.month,state.week),weekly=advanceAstralRiftWeekly({directives:astralRiftWeeklyDirectives(state.year,state.month,state.week),progress:state.astralRiftWeeklyKey===weekKey?state.astralRiftWeeklyProgress:{},rewardedKeys:state.rewardedAstralRiftDirectives,weekKey,event:{riftId:action.riftId,grade:resolved.grade,success:true}}),earned=newlyEarnedAstralRiftHonors(records,state.claimedAstralRiftHonors),fx=legacyPathEffects(state.sanctuaryLegacyPath),journeyKey=`${state.year}-${state.month}`;return{...state,astralRiftRecords:records,astralRiftEchoes:state.astralRiftEchoes+resolved.echoes+weekly.echoes,astralRiftWeeklyKey:weekKey,astralRiftWeeklyProgress:weekly.progress,rewardedAstralRiftDirectives:weekly.rewardedKeys,claimedAstralRiftHonors:[...state.claimedAstralRiftHonors,...earned.map(i=>i.id)],gold:state.gold+earned.reduce((s,i)=>s+i.reward.gold,0),gems:state.gems+earned.reduce((s,i)=>s+i.reward.gems,0),seasonJourneyScores:{...state.seasonJourneyScores,[journeyKey]:(state.seasonJourneyScores[journeyKey]??0)+fx.expeditionJourney}};}
 const baseNext=Base.reducer(state,action as Base.Action);if(baseNext===state)return state;let next:GameState={...baseNext,...endgameState(state)};const fx=legacyPathEffects(state.sanctuaryLegacyPath);if(action.type==='NEXT_MONTH'&&state.sanctuaryLegacyPath==='keeper'){const stats={...next.stats,fatigue:Math.max(0,next.stats.fatigue-fx.fatigueRecovery),stress:Math.max(0,next.stats.stress-fx.stressRecovery)};next={...next,stats,condition:Base.deriveCondition(stats)};}return next;
}
