import {describe,expect,it} from 'vitest';
import type {MobileWorldRecommendation} from './mobile-category-guidance';
import {clearWorldQuest,isQuestResolved,loadWorldQuest,loadWorldQuestHistory,npcQuestProgress,npcQuestRank,questFromRecommendation,recordWorldQuestCompletion,saveWorldQuest,WORLD_QUEST_HISTORY_KEY,WORLD_QUEST_STORAGE_KEY} from './world-quest-contract';
const reward:MobileWorldRecommendation={feature:'achievements',category:'growth',label:'성장 업적 수령',description:'보상 확인',reason:'바로 받을 보상이 있습니다.',priority:'reward'};const routine:MobileWorldRecommendation={feature:'schedule',category:'life',label:'이번 주 스케줄',description:'일정 확인',reason:'이번 주 행동을 정합니다.',priority:'routine'};
function memoryStorage(){const values=new Map<string,string>();return {getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>{values.set(key,value);},removeItem:(key:string)=>{values.delete(key);}};}
describe('world quest contracts',()=>{
 it('turns a recommendation into a stable NPC-issued contract',()=>{const quest=questFromRecommendation(reward,new Date('2026-09-19T00:00:00.000Z'));expect(quest).toMatchObject({id:'growth:achievements',feature:'achievements',category:'growth',title:'성장 업적 수령',issuerId:'arin',issuerName:'아린'});expect(quest.acceptedAt).toBe('2026-09-19T00:00:00.000Z');});
 it('keeps the quest active until the recommended objective changes',()=>{const quest=questFromRecommendation(reward);expect(isQuestResolved(quest,reward)).toBe(false);expect(isQuestResolved(quest,routine)).toBe(true);});
 it('persists accepted quests across feature screens and clears completed quests',()=>{const storage=memoryStorage();const quest=questFromRecommendation(reward);saveWorldQuest(storage,quest);expect(loadWorldQuest(storage)).toEqual(quest);clearWorldQuest(storage);expect(storage.getItem(WORLD_QUEST_STORAGE_KEY)).toBeNull();});
 it('loads legacy contracts without an issuer so existing saves remain valid',()=>{const storage=memoryStorage();storage.setItem(WORLD_QUEST_STORAGE_KEY,JSON.stringify({id:'life:schedule',feature:'schedule',category:'life',title:'일정',reason:'이유',acceptedAt:'2026-09-18T00:00:00.000Z'}));expect(loadWorldQuest(storage)?.title).toBe('일정');});
 it('records NPC-specific totals and a bounded recent journal',()=>{const storage=memoryStorage();const growth=questFromRecommendation(reward);const life=questFromRecommendation(routine);recordWorldQuestCompletion(storage,growth,new Date('2026-09-19T01:00:00.000Z'));recordWorldQuestCompletion(storage,growth,new Date('2026-09-19T02:00:00.000Z'));const history=recordWorldQuestCompletion(storage,life,new Date('2026-09-19T03:00:00.000Z'));expect(history.completed).toBe(3);expect(history.completedByIssuer).toEqual({arin:2,momo:1});expect(history.recent.map(entry=>entry.issuerName)).toEqual(['모모','아린','아린']);expect(history.recent[0].title).toBe('이번 주 스케줄');});
 it('migrates old history without losing its cumulative total',()=>{const storage=memoryStorage();storage.setItem(WORLD_QUEST_HISTORY_KEY,JSON.stringify({completed:7,lastCompletedAt:'2026-09-18T00:00:00.000Z',lastTitle:'옛 의뢰',lastIssuerName:'아린'}));const history=loadWorldQuestHistory(storage);expect(history.completed).toBe(7);expect(history.completedByIssuer).toEqual({});expect(history.recent).toEqual([]);});
 it('maps repeated NPC completions to visible trust ranks',()=>{expect([0,1,5,10,20].map(npcQuestRank)).toEqual(['첫 만남','첫 의뢰 완료','단골 모험가','신뢰받는 동료','전설의 동료']);});
 it('shows exact progress to the next NPC quest-chain milestone',()=>{expect(npcQuestProgress(0)).toEqual({rank:'첫 만남',nextRank:'첫 의뢰 완료',nextAt:1,remaining:1,percent:0});expect(npcQuestProgress(3)).toEqual({rank:'첫 의뢰 완료',nextRank:'단골 모험가',nextAt:5,remaining:2,percent:50});expect(npcQuestProgress(20)).toEqual({rank:'전설의 동료',nextRank:null,nextAt:null,remaining:0,percent:100});});
 it('repairs corrupt history and corrupt active quest data without blocking the hub',()=>{const storage=memoryStorage();storage.setItem(WORLD_QUEST_STORAGE_KEY,'{"feature":42}');storage.setItem(WORLD_QUEST_HISTORY_KEY,'broken');expect(loadWorldQuest(storage)).toBeNull();expect(loadWorldQuestHistory(storage).completed).toBe(0);});
});
